### ISSUE TITLE
Sync changes beyond the initial range

### ISSUE THREAD

**Issue by axellorreyne** [SolidLabResearch/google-sheet-sync#7]
The synchronisation agent will now only check, convert and write back changes to the pod that are included in the initial range.
This range is based on the data that is queried from the resource and first written to the Google Sheet during the initial cold start of the agent.

Instead, the agent should check every sync cycle what the used range is of the Google Sheet and, if necessary, be able to create more quads instead of only being able to edit or delete old ones.

**Comment by bjdmeest** [comment]
Yeah, so I'm envisioning that I'll create 1 data item as RDF, and then use google sheets to manage 10s or 100s, e.g. the books.ttl: I create 1 book in turtle and then edit 100s using google sheets. I assume this challenge would fix that

**Comment by pheyvaer** [comment]
At the moment there is a limited workaround at https://github.com/SolidLabResearch/google-sheet-sync/blob/main/src/google.js#L81C1-L81C1. But that will only work to a certain extend.

**Comment by sevrijss** [comment]
Possibly fixed in #14 by using the Sheet name instead of a fixed range.
